# Generated by Django 5.0.4 on 2024-04-11 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_verifyotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifyotp',
            name='emp',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.employee'),
        ),
    ]
